version: "3.8"

services:
  # Database - MariaDB
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: teste_receitas_rg_sistemas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "9002:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "admin",
          "-padmin",
        ]
      timeout: 20s
      retries: 10
      interval: 10s
    networks:
      - app-network

  # API Server - Node.js + TypeScript
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # Client - Vue.js + Nginx
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:80"
    depends_on:
      - server
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
